var $ = require('jquery');
require('angular');
require('angular-route');
require('./controllers/lobby-controller');
require('./controllers/game-controller');
require('./routes');
require('./components/websocket');
require('./components/md5');
require('./components/players');
require('./components/paint');
require('./components/joystick')($);
